
#without valid cookie
Get http://localhost:3000/api/users

###
#with valid cookie
POST http:http://localhost:3000/api/users
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtYmllLmoyMTBAZ21haWwuY29tIiwiaWF0IjoxNTYxMDM1OTk5fQ.SPzGskiOdv_Mohp0-rDAIBwEmyFqm-jfeULY1iCaj34
